import { useState } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const LAST_UPDATED = 'June 2025';

const SECTIONS = [
  {
    id: 'who-we-are',
    title: '1. Who We Are',
    body: `Giviit Technologies Ltd ("Giviit", "we", "our", or "us") operates the crowdfunding platform at Giviit.ng. We are incorporated in Nigeria and committed to complying with the Nigeria Data Protection Regulation (NDPR) 2019 and the Nigeria Data Protection Act 2023.

If you have questions about this policy, contact our Data Protection Officer at: privacy@Giviit.ng`,
  },
  {
    id: 'information-we-collect',
    title: '2. Information We Collect',
    body: `We collect information you give us directly and information generated by your use of our platform.

Account information: Full name, email address, phone number, password (hashed), profile photo.

Identity verification: NIN (National Identification Number) and government-issued ID documents (submitted for KYC). These are processed solely for fraud prevention and identity verification and are never displayed publicly.

Bank details: Account name, number, and bank name â€” used only to process withdrawal requests.

Campaign content: Titles, descriptions, photos, videos, and any other content you submit to a campaign.

Transaction data: Donation amounts, Paystack payment references, timestamps, and whether a donation was anonymous.

Device and usage data: IP address, browser type, pages visited, referring URLs, and session timestamps â€” collected automatically via cookies and server logs.

Communications: Emails, support tickets, and messages you send to us.`,
  },
  {
    id: 'how-we-use',
    title: '3. How We Use Your Information',
    body: `We use your information to:

â€” Create and manage your account and verify your identity
â€” Publish and manage your fundraising campaigns
â€” Process donations and withdrawals via Paystack
â€” Send transactional emails (receipts, withdrawal confirmations, campaign approvals)
â€” Detect and prevent fraud, abuse, and unauthorised access
â€” Respond to your support requests
â€” Send product updates and newsletters (only with your consent â€” you can unsubscribe at any time)
â€” Comply with our legal obligations under Nigerian law`,
  },
  {
    id: 'legal-basis',
    title: '4. Legal Basis for Processing',
    body: `Under the NDPR, we process your personal data on the following bases:

Contract performance: Processing necessary to provide our services (account creation, donations, withdrawals).

Legitimate interests: Fraud prevention, platform security, and improving our services.

Consent: Marketing emails and newsletters. You can withdraw consent at any time by clicking "Unsubscribe" in any email.

Legal obligation: Compliance with FIRS, EFCC, and other Nigerian regulatory requirements.`,
  },
  {
    id: 'sharing',
    title: '5. Sharing Your Information',
    body: `We do not sell your personal data. We share it only with:

Paystack Technologies Ltd â€” to process payments securely. Paystack's privacy policy governs their use of your payment data.

Cloudinary Inc â€” to store and serve images you upload.

Resend / SMTP providers â€” to deliver transactional and marketing emails.

Supabase Inc â€” our database and authentication provider.

Law enforcement and regulators â€” if required by a valid Nigerian court order, warrant, or applicable law.

We require all third-party processors to maintain appropriate data security standards.`,
  },
  {
    id: 'identity-documents',
    title: '6. Identity Documents',
    body: `NIN and government ID documents submitted for KYC are:

â€” Encrypted at rest and in transit
â€” Accessible only to authorised Giviit verification staff
â€” Never displayed publicly or shared with other users
â€” Retained for 3 years after account closure to comply with Nigerian AML/CFT obligations, then securely deleted

We do not store raw NIN numbers in plaintext after verification is complete.`,
  },
  {
    id: 'retention',
    title: '7. Data Retention',
    body: `Account data is retained for as long as your account is active. If you delete your account, we will delete or anonymise your personal data within 90 days, except where retention is required by law (e.g. financial transaction records retained for 6 years under CAMA 2020).

Campaign content and donation history may be retained in anonymised form for statistical purposes.`,
  },
  {
    id: 'your-rights',
    title: '8. Your Rights',
    body: `Under the NDPR, you have the right to:

Access â€” request a copy of the personal data we hold about you.
Correction â€” ask us to correct inaccurate data.
Deletion â€” request deletion of your data (subject to legal retention requirements).
Objection â€” object to processing based on legitimate interests.
Data portability â€” receive your data in a structured, machine-readable format.
Withdraw consent â€” for any processing based on consent (e.g. marketing emails).

To exercise any right, email privacy@Giviit.ng. We will respond within 30 days. You may also lodge a complaint with the National Information Technology Development Agency (NITDA).`,
  },
  {
    id: 'security',
    title: '9. Security',
    body: `We implement industry-standard security measures including:

â€” TLS 1.2+ encryption for all data in transit
â€” AES-256 encryption for sensitive data at rest
â€” Role-based access controls limiting staff access to personal data
â€” Regular security audits and penetration testing
â€” Supabase Row Level Security (RLS) on all database tables

No system is perfectly secure. If you believe your account has been compromised, contact support@Giviit.ng immediately.`,
  },
  {
    id: 'cookies',
    title: '10. Cookies',
    body: `We use cookies and similar technologies to operate our platform. See our Cookie Policy at Giviit.ng/cookie-policy for full details, including how to manage your cookie preferences.`,
  },
  {
    id: 'children',
    title: '11. Children',
    body: `Giviit is not directed at children under 18. We do not knowingly collect personal data from anyone under 18. If you believe a minor has created an account, contact privacy@Giviit.ng and we will delete the account.`,
  },
  {
    id: 'changes',
    title: '12. Changes to This Policy',
    body: `We may update this policy from time to time. When we make material changes, we will notify you by email and update the "Last updated" date below. Continued use of Giviit after changes take effect constitutes acceptance of the updated policy.`,
  },
  {
    id: 'contact',
    title: '13. Contact',
    body: `Giviit Technologies Ltd
Data Protection Officer
Email: privacy@Giviit.ng
Address: Lagos, Nigeria

For urgent data protection concerns, you may also contact NITDA at: nitda.gov.ng`,
  },
];

const NAV_ITEMS = SECTIONS.map(s => ({ id: s.id, label: s.title.replace(/^\d+\.\s/, '') }));

export default function PrivacyPolicyPage() {
  const [active, setActive] = useState(null);

  const scrollTo = (id) => {
    const el = document.getElementById(id);
    if (el) {
      const top = el.getBoundingClientRect().top + window.scrollY - 96;
      window.scrollTo({ top, behavior: 'smooth' });
      setActive(id);
    }
  };

  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <div className="pt-16">

        {/* Header */}
        <div className="bg-dark text-white py-16 px-4">
          <div className="max-w-5xl mx-auto">
            <p className="text-primary text-xs font-bold uppercase tracking-widest mb-3">Legal</p>
            <h1 className="text-4xl sm:text-5xl font-black mb-4">Privacy Policy</h1>
            <p className="text-gray-400 text-sm max-w-xl">
              We take your privacy seriously. This policy explains exactly what data we collect, why, and what rights you have over it.
            </p>
            <p className="text-gray-500 text-xs mt-4">Last updated: <span className="text-gray-300">{LAST_UPDATED}</span></p>
          </div>
        </div>

        <div className="max-w-5xl mx-auto px-4 py-14">

          {/* Summary box */}
          <div className="border-l-4 border-primary bg-primary/5 pl-5 pr-4 py-4 rounded-r-xl mb-14">
            <p className="text-gray-700 text-sm leading-relaxed">
              <strong className="text-dark">Summary:</strong> Giviit collects your name, email, and payment details to operate the platform. We never sell your data. You can request deletion of your account at any time by emailing privacy@Giviit.ng. Nigerian NDPR compliance applies.
            </p>
            <div className="flex flex-wrap gap-4 mt-3">
              <Link to="/terms" className="text-primary text-xs font-semibold hover:underline">Terms of Service â†’</Link>
              <Link to="/cookie-policy" className="text-primary text-xs font-semibold hover:underline">Cookie Policy â†’</Link>
            </div>
          </div>

          <div className="flex flex-col lg:flex-row gap-10">

            {/* Sidebar */}
            <aside className="hidden lg:block w-60 flex-shrink-0">
              <div className="sticky top-24 bg-gray-50 border border-gray-200 rounded-2xl p-4">
                <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-3 px-1">Sections</p>
                <nav className="space-y-0.5">
                  {NAV_ITEMS.map(({ id, label }) => (
                    <button
                      key={id}
                      onClick={() => scrollTo(id)}
                      className={`w-full text-left text-xs px-3 py-2 rounded-lg transition-colors leading-snug ${
                        active === id
                          ? 'bg-primary text-white font-semibold'
                          : 'text-gray-600 hover:bg-gray-100 hover:text-dark'
                      }`}
                    >
                      {label}
                    </button>
                  ))}
                </nav>
              </div>
            </aside>

            {/* Content */}
            <div className="flex-1 min-w-0 space-y-12">
              {SECTIONS.map(({ id, title, body }) => (
                <section key={id} id={id} className="scroll-mt-24">
                  <h2 className="text-lg font-bold text-dark mb-4 pb-2 border-b border-gray-100">{title}</h2>
                  <div className="text-gray-600 text-sm leading-relaxed whitespace-pre-line">{body}</div>
                </section>
              ))}

              <div className="pt-8 border-t border-gray-100 flex flex-wrap gap-4">
                <Link to="/terms" className="text-primary text-sm font-semibold hover:underline">Terms of Service</Link>
                <Link to="/cookie-policy" className="text-primary text-sm font-semibold hover:underline">Cookie Policy</Link>
                <a href="mailto:privacy@Giviit.ng" className="text-primary text-sm font-semibold hover:underline">privacy@Giviit.ng</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}

